export const ADD_ING = 'ADD_INGREDIENT'
export const REMOVE_ING = 'REMOVE_INGREDIENT'
export const INIT_ING = 'SET_INGREDIENTS'
export const INIT_ING_ERROR = 'SET_INGREDIENTS_ERROR'

export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES' 
export const PURCHASE_BURGER_ERROR = 'PURCHASE_BURGER_ERROR' 
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'