export const ADD_ING = 'ADD_INGREDIENT'
export const REMOVE_ING = 'REMOVE_INGREDIENT'
export const INIT_ING = 'SET_INGREDIENTS'
export const INIT_ING_ERROR = 'SET_INGREDIENTS_ERROR'

export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES' 
export const PURCHASE_BURGER_ERROR = 'PURCHASE_BURGER_ERROR' 
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT'


export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
